/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hawkfranklin.aura.ui.theme

import androidx.compose.ui.graphics.Color

// Aura palette (gold + cyan on deep-void) -> Updated for Nimbo brand (terracotta + cream)
val primaryLight = Color(0xFFCD410B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFECE7)
val onPrimaryContainerLight = Color(0xFF3A0B00)
val secondaryLight = Color(0xFFCD410B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFECE7)
val onSecondaryContainerLight = Color(0xFF3A0B00)
val tertiaryLight = Color(0xFF7C5AE6)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE6DCFF)
val onTertiaryContainerLight = Color(0xFF2B1C4D)
val errorLight = Color(0xFFB3261E)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFF9DEDC)
val onErrorContainerLight = Color(0xFF8C1D18)
val backgroundLight = Color(0xFFFDF6ED)
val onBackgroundLight = Color(0xFF1A1A1A)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF1A1A1A)
val surfaceVariantLight = Color(0xFFF0EDE8)
val onSurfaceVariantLight = Color(0xFF6B7280)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFDF6ED)
val surfaceContainerLight = Color(0xFFFAF2E8)
val surfaceContainerHighLight = Color(0xFFEBE8E3)
val surfaceContainerHighestLight = Color(0xFFE0DDD9)
val inverseSurfaceLight = Color(0xFF1A1A1A)
val inverseOnSurfaceLight = Color(0xFFFDF6ED)
val outlineLight = Color(0xFF6B7280)
val outlineVariantLight = Color(0xFFE0DDD9)
val inversePrimaryLight = Color(0xFFCD410B)
val surfaceDimLight = Color(0xFFEBE8E3)
val surfaceBrightLight = Color(0xFFFFFFFF)
val scrimLight = Color(0xFF000000)

val primaryDark = Color(0xFFCD410B)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF4A1502)
val onPrimaryContainerDark = Color(0xFFFFECE7)
val secondaryDark = Color(0xFFCD410B)
val onSecondaryDark = Color(0xFFFFFFFF)
val secondaryContainerDark = Color(0xFF4A1502)
val onSecondaryContainerDark = Color(0xFFFFECE7)
val tertiaryDark = Color(0xFFBFA7FF)
val onTertiaryDark = Color(0xFF2A1B4D)
val tertiaryContainerDark = Color(0xFF3A2B5E)
val onTertiaryContainerDark = Color(0xFFE6DCFF)
val errorDark = Color(0xFFF2B8B5)
val onErrorDark = Color(0xFF601410)
val errorContainerDark = Color(0xFF8C1D18)
val onErrorContainerDark = Color(0xFFF9DEDC)
val backgroundDark = Color(0xFF0D0D0F)
val onBackgroundDark = Color(0xFFF5F5F4)
val surfaceDark = Color(0xFF1A1A1E)
val onSurfaceDark = Color(0xFFF5F5F4)
val surfaceVariantDark = Color(0xFF26262B)
val onSurfaceVariantDark = Color(0xFF9CA3AF)
val surfaceContainerLowestDark = Color(0xFF0D0D0F)
val surfaceContainerLowDark = Color(0xFF151518)
val surfaceContainerDark = Color(0xFF1A1A1E)
val surfaceContainerHighDark = Color(0xFF222227)
val surfaceContainerHighestDark = Color(0xFF2B2B31)
val inverseSurfaceDark = Color(0xFFF5F5F4)
val inverseOnSurfaceDark = Color(0xFF0D0D0F)
val outlineDark = Color(0xFF9CA3AF)
val outlineVariantDark = Color(0xFF4B4B52)
val inversePrimaryDark = Color(0xFFCD410B)
val surfaceDimDark = Color(0xFF151518)
val surfaceBrightDark = Color(0xFF222227)
val scrimDark = Color(0xFF000000)

// Aura theme palette (purple/void)
val primaryAura = Color(0xFF6366F1)
val onPrimaryAura = Color(0xFFFFFFFF)
val primaryContainerAura = Color(0xFF312E81)
val onPrimaryContainerAura = Color(0xFFE0E7FF)
val secondaryAura = Color(0xFFA855F7)
val onSecondaryAura = Color(0xFFFFFFFF)
val secondaryContainerAura = Color(0xFF4C1D95)
val onSecondaryContainerAura = Color(0xFFE9D5FF)
val tertiaryAura = Color(0xFF818CF8)
val onTertiaryAura = Color(0xFF0F172A)
val tertiaryContainerAura = Color(0xFF1E1B4B)
val onTertiaryContainerAura = Color(0xFFE0E7FF)
val errorAura = Color(0xFFFCA5A5)
val onErrorAura = Color(0xFF4C0519)
val errorContainerAura = Color(0xFF3B0A1E)
val onErrorContainerAura = Color(0xFFFEE2E2)
val backgroundAura = Color(0xFF020617)
val onBackgroundAura = Color(0xFFE2E8F0)
val surfaceAura = Color(0xFF0F172A)
val onSurfaceAura = Color(0xFFE2E8F0)
val surfaceVariantAura = Color(0xFF1E293B)
val onSurfaceVariantAura = Color(0xFF94A3B8)
val surfaceContainerLowestAura = Color(0xFF0A0F1A)
val surfaceContainerLowAura = Color(0xFF0D1422)
val surfaceContainerAura = Color(0xFF121A2B)
val surfaceContainerHighAura = Color(0xFF182236)
val surfaceContainerHighestAura = Color(0xFF1E2A42)
val inverseSurfaceAura = Color(0xFFE2E8F0)
val inverseOnSurfaceAura = Color(0xFF0F172A)
val outlineAura = Color(0xFF334155)
val outlineVariantAura = Color(0xFF1E293B)
val inversePrimaryAura = Color(0xFFC7D2FE)
val surfaceDimAura = Color(0xFF0B1220)
val surfaceBrightAura = Color(0xFF1E293B)
val scrimAura = Color(0xFF000000)
